[package]
name = "tray-emergency-hue"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
notify-rust = "4.11.4"
simplelog = "0.12.2"
tray-item = "0.10.0"

[build-dependencies]
embed-resource = "3.0.1"
